export const synonymMap = {
    nombre: ["nombre", "nombres", "apellido",  "Sofía",
    "Valentina",
    "Isabella",
    "Camila",
    "Valeria",
    "Mariana",
    "Gabriela",
    "Victoria",
    "Lucía",
    "Martina",
    "José",
    "Luis",
    "Carlos",
    "Juan",
    "Andrés",
    "Diego",
    "Fernando",
    "Miguel",
    "Alejandro",
    "Daniel","Pedro",
    "Santiago",
    "Sebastián",
    "Matías",
    "Nicolás",
    "Samuel",
    "Alejandro",
    "David",
    "Benjamín",
    "Lucas",
    "Emma",
    "Mía",
    "Antonella",
    "Olivia",
    "Regina",
    "Fernanda",
    "Paula",
    "Emilia",
    "Renata",
    "Salomé",
    "Angel",
    "Leonardo",
    "Rodrigo",
    "Francisco",
    "Antonio",
    "Joaquín",
    "Tomás",
    "Manuel",
    "Gustavo",
    "Rafael",
    "Paola",
    "Laura",
    "Andrea",
    "Patricia",
    "Verónica",
    "Elizabeth",
    "Karla",
    "Diana",
    "Carla",
    "Adriana",
    "Julia",
    "Ana",
    "Violeta",
    "Esteban",
    "Agustín",
    "Javier",
    "Ramón",
    "Rubén",
    "Eduardo",
    "Armando", "Roberto",
    "Ángel",
    "Christian",
    "Franco",
    "Gabriel",
    "Ignacio",
    "Jorge",
    "Josué",
    "Julio",
    "Mario",
    "Martín",
    "Maximiliano",
    "Oscar",
    "Pablo",
    "Sergio",
    "Alex",
    "Alonso",
    "César",
    "Edgar",
    "Gerardo",
    "Hugo",
    "Isaac",
    "Ricardo",
    "Víctor",
    "Carolina",
    "Catalina",
    "Clara",
    "Daniela",
    "Elisa",
    "Elsa",
    "Fabiana",
    "Gabriella",
    "Giuliana",
    "Inés",
    "Irene",
    "Isabel",
    "Jimena",
    "Joanna",
    "Juana",
    "Luciana",
    "Luna",
    "Magdalena",
    "María",
    "Marisol",
    "Miranda",
    "Norma",
    "Raquel",
    "Sara",
    "Teresa",
    "Yolanda","Alfredo",
    "Arturo",
    "Adrián",
    "Bruno",
    "Claudio",
    "Domingo",
    "Enrique",
    "Ernesto",
    "Felipe",
    "Guillermo",
    "Horacio",
    "Iván",
    "Jaime",
    "León",
    "Lorenzo",
    "Marcelo",
    "Néstor",
    "Orlando",
    "Patricio",
    "Raúl",
    "René",
    "Simón",
    "Ulises",
    "Emilio",
    "Federico",
    "Flavio",
    "Gonzalo",
    "Gregorio",
    "Hernán",
    "Ismael",
    "Julián",
    "Kevin",
    "Leonel",
    "Luciano",
    "Mauricio",
    "Noel",
    "Norberto",
    "Pepe",
    "Quintín",
    "Reynaldo",
    "Salvador",
    "Thiago",
    "Valentín",
    "Xavier",
    "Yago",
    "Zacarías",
    "Alicia",
    "Alma",
    "Amanda",
    "Amelia",
    "Ana Paula", "soy", "me llamo", "mi apodo es", "apelativo", "denominación", "cognombre", "identificación, "],
    genero: ['genero', 'género', 'sexo', 'sex', 'sexo', "hombre", "mujer", "identidad de género", "orientación sexual", "masculino",   "género",
    "sexo",
    "identidad de género",
    "orientación sexual",
    "masculino",
    "femenino",
    "no binario",
    "transgénero",
    "cisgénero",
    "intersexual",
    "androgíneo",
    "trans",
    "cis",
    "identidad sexual",
    "expresión de género",
    "diferenciación sexual",
    "características sexuales",
    "atributos de género",
    "roles de género",
    "binarismo de género",
    "espectro de género",
    "fluidez de género",
    "queer",
    "género diverso",
    "identificación sexual",
    "orientación de género","femenino", "no binario"],
    alergia: ['alergia',   "alergia",
    "alérgico",
    "alérgica",
    "reacción alérgica",
    "hipersensibilidad",
    "intolerancia",
    "sensibilidad",
    "reacción de hipersensibilidad",
    "reacción adversa",
    "sensibilidad aumentada",
    "respuesta inmunitaria exagerada",
    "incompatibilidad",
    "desencadenante alérgico",
    "anafilaxia",
    "asma alérgico",
    "dermatitis atópica",
    "eczema",
    "urticaria",
    "rinitis alérgica",
    "conjuntivitis alérgica",
    "choque anafiláctico",
    "síndrome de alergia oral","reacción inmediata",
    "reacción retardada",
    "alergenos",
    "pruebas de alergia",
    "antígenos",
    "inmunoglobulina E",
    "hipoalergénico",
    "alergia estacional",
    "alergia perenne",
    "alergia alimentaria",
    "alergia a los ácaros del polvo",
    "alergia al polen",
    "alergia a las mascotas",
    "alergia al látex",
    "alergia a los medicamentos",
    "alergia al moho",
    "prick test",
    "test de parche",
    "desensibilización",
    "inmunoterapia",
    "autoinyector de epinefrina",
    "antihistamínicos",
    "corticosteroides",
    "broncodilatadores",
    "alergólogo",
    "evitar alérgenos",
    "contaminación cruzada",
    "epitopo",
    "alérgeno potencial",
    "factor desencadenante",
    "reacción cruzada",
    "sensibilización",
    "tolerancia inmunológica",
    "reacción exacerbada",
    "alergia ocupacional",
    "asma ocupacional",
    "dermatitis de contacto",
    "prueba de provocación",
    "eliminación de alérgenos",
    "dieta de eliminación",
    "intolerancia alimentaria",
    "pseudoalergia",
    "reacción no alérgica",
    "hipersensibilidad no alérgica",
    "síndrome de alergia no alérgica",
    "mediadores de la inflamación",
    "respuesta inmune",
    "proteínas de transferencia de lípidos",
    "alergia al níquel",
    "alergia a los sulfitos",
    "reacciones de fase tardía",'alérgico', 'alérgica', 'alérgias', 'alergias', 'alergico', 'alérgic@', "no me gusta", "me cae mal", "me hace mal", "hipersensibilidad", "intolerancia", "aversión", "reacción alérgica"],
    comida: ['comida', 'plato', 'platillo', 'alimento', 'alimentación', 'comidita', "me gusta", "siempre como", "manjar", "sustento", "vianda", "nutritivo", "alimenticio",   "Asado",
    "Empanadas argentinas",
    "Choripán",
    "Milanesa a la napolitana",
    "Dulce de leche",
    "Salteñas",
    "Pique macho",
    "Silpancho",
    "Anticuchos",
    "Ceviche peruano",
    "Lomo saltado",
    "Ají de gallina",
    "Tacos al pastor",
    "Chiles en nogada",
    "Pozole",
    "Feijoada",
    "Moqueca",
    "Pão de queijo",
    "Arepas",
    "Pabellón criollo","Hallacas venezolanas",
    "Carne en vara",
    "Tequeños",
    "Chupe de camarones",
    "Tamales",
    "Mondongo",
    "Sancocho",
    "Lechona",
    "Bandeja paisa",
    "Ajiaco",
    "Cazuela de mariscos",
    "Encebollado",
    "Seco de pollo",
    "Cuy asado",
    "Locro",
    "Sopa paraguaya",
    "Chipa guasu",
    "Pira caldo",
    "Sopa de maní",
    "Pastel de choclo","Ropa vieja",
    "Arroz con pollo",
    "Gallo pinto",
    "Casado",
    "Plátanos fritos",
    "Picadillo",
    "Chimichurri",
    "Matambre",
    "Vitel toné",
    "Barbacoa",
    "Cochinita pibil",
    "Mole poblano",
    "Enchiladas",
    "Tostadas",
    "Churrasco",
    "Feijão tropeiro",
    "Bobó de camarão",
    "Acargajé",
    "Empanadas chilenas",
    "Curanto",],
    objetivos: ['objetivos',  "condición física",
    "forma física",
    "tonificación",
    "definición muscular",
    "masa muscular",
    "fuerza",
    "resistencia",
    "capacidad aeróbica",
    "flexibilidad",
    "agilidad",
    "equilibrio",
    "potencia",
    "vigor",
    "salud",
    "bienestar",
    "rendimiento físico",
    "aptitud física",
    "cuerpo atlético",
    "composición corporal",
    "índice de masa corporal",
    "grasa corporal",
    "peso saludable",
    "estamina",
    "energía",
    "vitalidad",
    "recuperación muscular",
    "estado de forma",
    "mejora física",
    "progreso físico",
    "acondicionamiento físico",
    "habilidad deportiva",
    "competencia física",
    "aptitud deportiva",
    "rendimiento deportivo",
    "nutrición deportiva",
    "entrenamiento de fuerza",
    "entrenamiento cardiovascular",
    "entrenamiento de resistencia",
    "entrenamiento funcional",
    "culturismo",
    "fitness",
    "preparación física",
    "mejora de la postura",
    "salud física", 'meta', 'metas', 'objetivo', 'propósito', 'aspiración', 'metita', 'propósitos', "quiero", "propósitos", "anhelos", "ambiciones", "engordar", "adelgazar", "ser musculoso", "deseos", "metas personales", "ser"],
    edad: ["tengo", "mi edad es", "años",  "edad",
    "años",
    "tengo",
    "mi edad es",
    "cumplo",
    "vividos",
    "de edad",
    "añitos",
    "primaveras",
    "otoños",
    "juvenil",
    "adolescente",
    "adulto",
    "mayor",
    "menor",
    "infante",
    "niño",
    "joven",
    "anciano",
    "vejez",
    "madurez",
    "adultez",
    "senectud",
    "infancia",
    "pubertad",
    "juventud",
    "tercera edad",
    "edad adulta",
    "etapa de vida",
    "periodo vital",
    "década",
    "generación",
    "coetáneo",
    "contemporáneo",
    "natalicio",
    "fecha de nacimiento",
    "cumpleaños",
    "aniversario de nacimiento",
    "luz del día (en sentido figurado de nacimiento)",
    "ser del año de la pera (coloquial para indicar una edad avanzada)",
    "tener más años que Matusalén (expresión coloquial para referirse a alguien muy anciano)","edad"]
  };